#!/usr/bin/env php
<?php
# Usage: tk config
# Summary: Accesses config variables

// Bootstrap!
require($_ENV['_TK_ROOT'] .'/share/init.php');

// Try to parse out args
$return = config();
unset($argv[0]);
foreach($argv as $arg)
{
	// If the var doesn't exist just return empty string
	if(!isset($return[$arg]))
		return '';

	// Drill down
	$return = $return[$arg];
}

// Show everything that's not an array
if(!is_array($return))
{
	echo $return . PHP_EOL;
}

// Show array keys
if(is_array($return))
{
	foreach(array_keys($return) as $key)
	{
		echo $key . PHP_EOL;
	}
}