#!/usr/bin/env bash
# Usage: Kills a database process by id

set -e

# Provide tk completions
if [ "$1" = "--complete" ]; then
  tk config databases
  exit
fi

# Get commands
mysql=$(eval tk config commands mysql)

# Get connection info
ip=$(eval tk config databases $1 ip)
user=$(eval tk config databases $1 user)
pass=$(eval tk config databases $1 pass)


eval $mysql -u $user -h $ip -p$pass -e "'KILL ${2}'"